# set colors
set -g default-terminal "${TERM}"
set -ag terminal-overrides ",xterm-256color:RGB"

# force bar to bottom
set -g status-position bottom

# reload tmux config
bind r source-file ~/.tmux.conf \; display "Reloaded tmux.conf!"

# rebind prefix to Ctrl + A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# make status bar transparent
set-option -g status-style bg=default

# set default shell
set-option -g default-shell /opt/homebrew/bin/fish

# start windows indexing from 1
set -g base-index 1

# kill pane without confirmation
bind-key x kill-pane

# don't notify if other windows have activities
setw -g monitor-activity off

# renumber windows on window close
set -g renumber-windows on

# split panes using | and -
bind - split-window -h
bind | split-window -v
unbind '"'
unbind %

# vim-like pane switching
set-window-option -g mode-keys vi
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

### Plugins ###

set -g @plugin 'catppuccin/tmux#v2.1.3'

# initialize tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Configure the catppuccin plugin
# set -g @catppuccin_flavor "mocha" # mocha, frappe, macchiato, latte

run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""

set -g status-bg "#1e2030"
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_right "W"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

# sensible rebinds
set -g @plugin 'tmux-plugins/tmux-sensible'

# resurrect session after reboot
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'off'

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# tiling window manager like binds
set -g @plugin 'jabirali/tmux-tilish'
set -g @tilish-default 'main-vertical'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
