[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#191724"
foreground = "#abb2bf"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[scrolling]
history = 1000
